pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@github.com:zero0608/docker-build.git
          - cd docker-build.git
          - git push --mirror git@github.com:zero0608/docker-build.git