pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
         
          # Clone all bit
          - git clone --bare git@bitbucket.org:tadinhdong/docker-build.git
          - cd docker-build.git
          # Push all into GitHub
          - git push --mirror git@github.com:zero0608/docker-build.git
